version: '2'
services:
    luker-app:
        image: luker
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://luker-postgresql:5432/luker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    luker-postgresql:
        extends:
            file: postgresql.yml
            service: luker-postgresql
