version: '2'
services:
    luker-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/luker/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=luker
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
